-- 012_payroll_and_vouchers_enhanced.sql
-- Mejoras en el sistema de vales y creación de tablas de nómina semanal

-- 1. Modificar KS_VALES para permitir vales de caja y fecha de inicio de cobro
ALTER TABLE KS_VALES 
MODIFY FC_IDFACTURA_FK INT NULL,
ADD COLUMN VL_FECHA_INICIO_COBRO DATE NULL;

-- 2. Tabla para el seguimiento individual de cada cuota de un vale
CREATE TABLE KS_VALE_CUOTAS (
  VC_IDCUOTA_PK INT AUTO_INCREMENT PRIMARY KEY,
  VC_NUMERO_CUOTA INT NOT NULL,
  VC_VALOR_CUOTA DECIMAL(15, 2) NOT NULL,
  VC_ESTADO ENUM('PENDIENTE', 'PAGADO', 'CANCELADO') DEFAULT 'PENDIENTE',
  VC_FECHA_COBRO DATE NOT NULL,
  
  VL_IDVALE_FK INT NOT NULL,

  CONSTRAINT FK_VALE_CUOTA_VALE
    FOREIGN KEY (VL_IDVALE_FK)
    REFERENCES KS_VALES(VL_IDVALE_PK)
    ON DELETE CASCADE
);

-- 3. Tabla de Nóminas (Lotes semanales)
CREATE TABLE KS_NOMINAS (
  NM_IDNOMINA_PK INT AUTO_INCREMENT PRIMARY KEY,
  NM_FECHA_INICIO DATE NOT NULL,
  NM_FECHA_FIN DATE NOT NULL,
  NM_TOTAL_PAGADO DECIMAL(15, 2) DEFAULT 0,
  NM_ESTADO ENUM('PROCESANDO', 'CERRADA', 'CONFIRMADA', 'ANULADA') DEFAULT 'PROCESANDO',
  NM_FECHA_CIERRE DATETIME NULL,
  NM_FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 4. Detalle de Nómina por Trabajador
CREATE TABLE KS_NOMINA_DETALLES (
  ND_IDDETALLE_PK INT AUTO_INCREMENT PRIMARY KEY,
  ND_BASE DECIMAL(15, 2) DEFAULT 0,
  ND_COMISIONES DECIMAL(15, 2) DEFAULT 0,
  ND_BONOS DECIMAL(15, 2) DEFAULT 0,
  ND_DEDUCCIONES_VALES DECIMAL(15, 2) DEFAULT 0,
  ND_TOTAL_NETO DECIMAL(15, 2) NOT NULL,
  
  NM_IDNOMINA_FK INT NOT NULL,
  TR_IDTRABAJADOR_FK INT NOT NULL,

  CONSTRAINT FK_ND_NOMINA
    FOREIGN KEY (NM_IDNOMINA_FK)
    REFERENCES KS_NOMINAS(NM_IDNOMINA_PK)
    ON DELETE CASCADE,
  
  CONSTRAINT FK_ND_TRABAJADOR
    FOREIGN KEY (TR_IDTRABAJADOR_FK)
    REFERENCES KS_TRABAJADORES(TR_IDTRABAJADOR_PK)
);

-- 5. Agregar índices para reporte e historial
CREATE INDEX IDX_VALE_CUOTA_ESTADO ON KS_VALE_CUOTAS(VC_ESTADO);
CREATE INDEX IDX_VALE_CUOTA_FECHA ON KS_VALE_CUOTAS(VC_FECHA_COBRO);
CREATE INDEX IDX_NOMINA_FECHAS ON KS_NOMINAS(NM_FECHA_INICIO, NM_FECHA_FIN);
CREATE INDEX IDX_NOMINA_ESTADO ON KS_NOMINAS(NM_ESTADO);
