-- 029_rename_adelantos_to_vales.sql
-- Renombrar tabla de adelantos a vales y actualizar prefijos de columnas

-- 1. Renombrar la tabla principal
RENAME TABLE KS_ADELANTOS TO KS_VALES;

-- 2. Renombrar columnas en la nueva tabla KS_VALES
ALTER TABLE KS_VALES
  CHANGE COLUMN AD_IDADELANTO_PK VL_IDVALE_PK INT AUTO_INCREMENT,
  CHANGE COLUMN AD_MONTO VL_MONTO DECIMAL(15, 2) NOT NULL,
  CHANGE COLUMN AD_FECHA VL_FECHA DATE NULL,
  CHANGE COLUMN AD_ESTADO VL_ESTADO ENUM('PENDIENTE', 'DESCONTADO', 'ANULADO') DEFAULT 'PENDIENTE',
  CHANGE COLUMN AD_OBSERVACIONES VL_OBSERVACIONES TEXT NULL,
  CHANGE COLUMN AD_FECHA_CREACION VL_FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CHANGE COLUMN AD_CUOTAS VL_CUOTAS INT NOT NULL DEFAULT 1,
  CHANGE COLUMN AD_CUOTAS_PAGADAS VL_CUOTAS_PAGADAS INT NOT NULL DEFAULT 0,
  CHANGE COLUMN AD_FECHA_DESEMBOLSO VL_FECHA_DESEMBOLSO DATE NULL,
  CHANGE COLUMN AD_FECHA_INICIO_COBRO VL_FECHA_INICIO_COBRO DATE NULL;

-- 3. Renombrar columna de deducciones en detalles de nómina
ALTER TABLE KS_NOMINA_DETALLES
  CHANGE COLUMN ND_DEDUCCIONES_ADELANTOS ND_DEDUCCIONES_VALES DECIMAL(15, 2) DEFAULT 0;
