-- 035_create_nomina_vales_table.sql
-- Crear tabla de relación para registrar los descuentos individuales de vales en cada nómina

CREATE TABLE KS_NOMINA_VALES (
  NV_IDNOMINA_VALE_PK INT AUTO_INCREMENT PRIMARY KEY,
  NM_IDNOMINA_FK INT NOT NULL,
  VL_IDVALE_PK INT NOT NULL,
  NV_MONTO_DESCONTADO DECIMAL(15, 2) NOT NULL,
  NV_FECHA_DESCUENTO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  
  CONSTRAINT FK_NOMINA_VALE_NOMINA
    FOREIGN KEY (NM_IDNOMINA_FK)
    REFERENCES KS_NOMINAS(NM_IDNOMINA_PK)
    ON DELETE CASCADE,
  
  CONSTRAINT FK_NOMINA_VALE_VALE
    FOREIGN KEY (VL_IDVALE_PK)
    REFERENCES KS_VALES(VL_IDVALE_PK)
    ON DELETE CASCADE
);
