-- 036_create_garantias_table.sql
-- Implementación del método de pago GARANTIA y tabla para deducciones

-- 1. Insertar el método de pago GARANTIA si no existe
INSERT INTO KS_METODOS_PAGO (MP_NOMBRE)
SELECT 'GARANTIA' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM KS_METODOS_PAGO WHERE MP_NOMBRE = 'GARANTIA');

-- 2. Crear tabla de Garantías
CREATE TABLE KS_GARANTIAS (
  GA_IDGARANTIA_PK INT AUTO_INCREMENT PRIMARY KEY,
  GA_FECHA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  GA_VALOR DECIMAL(15,2) NOT NULL,
  
  FC_IDFACTURA_NUEVA_FK INT NOT NULL,
  FD_IDDETALLE_ORIGINAL_FK INT NOT NULL,
  TR_IDTECNICO_ORIGINAL_FK INT NOT NULL,

  CONSTRAINT FK_GARANTIA_NUEVA_FACTURA 
    FOREIGN KEY (FC_IDFACTURA_NUEVA_FK) 
    REFERENCES KS_FACTURAS(FC_IDFACTURA_PK),
    
  CONSTRAINT FK_GARANTIA_DETALLE_ORIGINAL 
    FOREIGN KEY (FD_IDDETALLE_ORIGINAL_FK) 
    REFERENCES KS_FACTURA_DETALLES(FD_IDDETALLE_PK),
    
  CONSTRAINT FK_GARANTIA_TECNICO_ORIGINAL 
    FOREIGN KEY (TR_IDTECNICO_ORIGINAL_FK) 
    REFERENCES KS_TRABAJADORES(TR_IDTRABAJADOR_PK)
);

-- 3. Alterar tabla KS_NOMINA_DETALLES para agregar la deducción
ALTER TABLE KS_NOMINA_DETALLES 
ADD COLUMN ND_DEDUCCIONES_GARANTIAS DECIMAL(15, 2) DEFAULT 0 AFTER ND_DEDUCCIONES_VALES;
